env:
  node: true
  es2021: true
extends:
  - airbnb-base
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
  import/extensions:
    - error
    - ignorePackages
    - js: always
